---
- name: Get disk space response
  hosts: all
  tasks:
    - name: Get disk space response
      shell: df "{{ item }}" --output=avail | tail -1
      loop:
        - /
        - /tmp
        - /home
      register: disk_freespace
      vars:
        item_path: "{{ item }}"
    
    - fail:
        msg: "{{ item_path }} does not have the minimum space required to continue (1Gb requested)."
      when: disk_freespace.results[ansible_loop.index0].stdout | float < 1048576
      loop: "{{ disk_freespace.results }}"
      loop_control:
        loop_var: item
