---
- name: Get disk space response
  hosts: all
  tasks:
    - name: Get disk space response
      shell: df "{{ item }}" --output=avail | tail -1
      loop:
        - /
        - /tmp
        - /home
      register: freespace
    
    - fail:
        msg: "{{ item }} does not have the minimum space required to continue (1Gb requested)."
      when: freespace.stdout|float is lt < 1048576
