---
- name: Cisco
  hosts: all
  gather_facts: true
  tasks:
    - debug:
        var: ansible_facts

    - name: Gather IOS Facts 02
      cisco.ios.ios_facts:
        gather_subset: all
      register: all_subset

    - name: Print Subset All 03
      ansible.builtin.debug:
        var: all_subset

    - name: Gather HW
      cisco.ios.ios_facts:
        gather_subset: hardware
      register: hw
    - name: Print HW
      ansible.builtin.debug:
        var: hw

    - name: Gather Int
      cisco.ios.ios_facts:
        gather_subset: interfaces
      register: int
      
    - name: Print Interfaces
      ansible.builtin.debug:
        var: int
