---
- name: Get disk space response
  hosts: all
  tasks:
    - name: Get disk space response
      shell: df "{{ item }}" --output=avail | tail -1
      loop:
        - /
        - /tmp
        - /home
      register: freespace
    
    - fail:
        msg: "{{ item.item }} does not have the minimum space required to continue (1Gb requested)."
      when: item.stdout_lines[0] | float < 1048576
      loop: "{{ freespace.results }}"
      loop_control:
        loop_var: item
